spring:
  application:
    name: Spring-API
  jwt:
    secret-key: ${JWT_SECRET}
    access-token: 7200 # 5m
    refresh-token: 604800 # 7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhook_secret_key: ${WEBHOOK_SECRET_KEY}
