spring:
  application:
    name: Spring-API
  datasource:
    url: jdbc:mysql://localhost:3306/spring-store-api?createDatabaseIfNotExist=true
    username: root
    password: shahadat.sdt.3301
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false