spring:
  application:
    name: Spring-API
  datasource:
    url: jdbc:mysql://localhost:3306/spring-store-api?createDatabaseIfNotExist=true
    username: root
    password: shahadat.sdt.3301
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false
  jwt:
    secret-key: ${JWT_SECRET}
    access-token: 7200 # 5m
    refresh-token: 604800 # 7d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhook_secret_key: ${WEBHOOK_SECRET_KEY}
webAppUrl: "http://localhost:3000/"